@echo off
set SPACE_PARTITIONS=1
set SPACE_HA=true
if %SPACE_HA%==true (set SPACE_BACKUPS=1) else (set SPACE_BACKUPS=0)
if %SPACE_HA%==true (set /A SPACE_INSTANCES=%SPACE_PARTITIONS% * 2) else (set SPACE_INSTANCES=%SPACE_PARTITIONS%)